apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source-orders-payment
spec:
  consumerGroup: payment
  bootstrapServers:
    - my-cluster-kafka-bootstrap.kafka:9092
  topics:
    - order-events
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: payment-saga
    uri: /reserve
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-sasl-auth
          key: username
      password:
        secretKeyRef:
          name: kafka-sasl-auth
          key: password